export { default as HeartSvg } from './heart-svg'
export { default as HeartRateSvg } from './heart-rate-svg'
export { default as AppleSvg } from './apple-svg'
export { default as AlarmClockSvg } from './alarm-clock-svg'
export { default as DumbbellSvg } from './dumbbell-svg'
export { default as TrophySvg } from './trophy-svg'
export { default as MountainSvg } from './mountain-svg'
export { default as PersonSvg } from './person-svg'
export { default as WalkingPersonSvg } from './walking-person-svg'
export { default as RunningPersonSvg } from './running-person-svg'
export { default as BicyclePersonSvg } from './bicycle-person-svg'
export { default as GooglePlaySvg } from './google-play-svg'
export { default as FinishMarkerFlagSvg } from './finish-marker-flag-svg'
export { default as StartMarkerSvg } from './start-marker-svg'
export { default as ResumeMarkerSvg } from './resume-marker-svg'
export { default as PauseMarkerSvg } from './pause-marker-svg'
export { default as RustoreSmallSvg } from './store/rustore-svg-s'
export { default as AppStoreSmallSvg } from './store/app-store-svg-s'
export { default as GooglePlaySmallSvg } from './store/google-play-svg-s'
export { default as AppGallerySmallSvg } from './store/app-gallery-svg-s'
export { default as VkSvg } from './vk-svg'
export { default as TgSvg } from './tg-svg'
export { default as TtSvg } from './tt-svg'
export { default as BurgerSvg } from './burger-svg'

export type { SvgIconProps } from './types'
