export enum ERRORS {
	INVALID_LENGTH = 'INVALID_LENGTH',
	INVALID_EMAIL = 'INVALID_EMAIL',
	DIGIT_REQUIRED = 'DIGIT_REQUIRED',

	MISMATCH = 'MISMATCH',
	TIMEOUT_EXPIRED = 'TIMEOUT_EXPIRED',

	NOT_FOUND = 'NOT_FOUND',
	BAD_REQUEST = 'BAD_REQUEST',
	UNAUTHORIZED = 'UNAUTHORIZED',
	FORBIDDEN = 'FORBIDDEN',
	INTERNAL = 'INTERNAL',

	ALREADY_CREATED = 'ALREADY_CREATED',
	ALREADY_EXISTS = 'ALREADY_EXISTS',

	USER_IN_NOT_FINISHED_TRAINING = 'USER_IN_NOT_FINISHED_TRAINING',
	USER_IS_TRAINING_PARTICIPANT = 'USER_IS_TRAINING_PARTICIPANT',
	USER_IS_NOT_TRAINING_PARTICIPANT = 'USER_IS_NOT_TRAINING_PARTICIPANT',

	UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
