export enum ERRORS {
    INVALID_LENGTH = 'INVALID_LENGTH',
    INVALID_EMAIL = 'INVALID_EMAIL',
    DIGIT_REQUIRED = 'DIGIT_REQUIRED',

    MISMATCH = 'MISMATCH',

    NOT_FOUND = 'NOT_FOUND',
    BAD_REQUEST = 'BAD_REQUEST',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    INTERNAL = 'INTERNAL',

    ALREADY_CREATED = 'ALREADY_CREATED',
    ALREADY_EXISTS = 'ALREADY_EXISTS',

    UNKNOWN_ERROR = 'UNKNOWN_ERROR'
}
