name: CI/CD Web Pipeline

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: '[backend] Install dependencies'
              run: cd backend && yarn install

            - name: '[backend] Symlink to shared'
              run: cd backend/src && ln -s ../../shared ./shared

            - name: '[backend] Run lint'
              run: cd backend && yarn lint

            - name: '[backend] Run build'
              run: cd backend && yarn build

            - name: '[frontend] Install dependencies'
              run: cd frontend && yarn install

            - name: '[frontend] Symlink to shared'
              run: cd frontend/src && ln -s ../../shared ./shared

            - name: '[frontend] Run lint'
              run: cd frontend && yarn lint

            - name: '[frontend] Run build'
              run: cd frontend && yarn build

    deploy:
        if: github.event_name == 'push'
        needs: checks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install sshpass
              run: |
                  sudo apt-get update
                  sudo apt-get install -y sshpass

            - name: Run deploy script via SSH with password
              env:
                  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
              run: |
                  sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no hiker@${{ secrets.SERVER_IP }} "
                    cd hikers-mobile && ./start.sh
                  "
