/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Phone.glb -t
*/

import * as THREE from 'three'
import React, { forwardRef, useMemo } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ScreenTextureURL, screenTextureURLs } from '@/consts/PhoneScreenTextures'

type GLTFResult = GLTF & {
	nodes: {
		Cylinder004: THREE.Mesh
		Cylinder004_1: THREE.Mesh
		Cylinder004_2: THREE.Mesh
		Cylinder004_3: THREE.Mesh
		Cylinder004_4: THREE.Mesh
		Lens001: THREE.Mesh
		Cylinder022: THREE.Mesh
		Cylinder022_1: THREE.Mesh
		Cylinder022_2: THREE.Mesh
		Cylinder022_3: THREE.Mesh
		Cylinder022_4: THREE.Mesh
		Lens002: THREE.Mesh
		Cylinder026: THREE.Mesh
		Cylinder026_1: THREE.Mesh
		Cylinder026_2: THREE.Mesh
		Cylinder026_3: THREE.Mesh
		Cylinder026_4: THREE.Mesh
		Lens003: THREE.Mesh
		Esfera: THREE.Mesh
		Esfera_1: THREE.Mesh
		Esfera_2: THREE.Mesh
		Back_Glass: THREE.Mesh
		Back_Mic_mesh: THREE.Mesh
		Cube001: THREE.Mesh
		Cube001_1: THREE.Mesh
		Cube001_2: THREE.Mesh
		Button_Action: THREE.Mesh
		Button_Power_OnOff: THREE.Mesh
		Button_Volume_Down: THREE.Mesh
		Button_Volume_Up: THREE.Mesh
		Camera_Control: THREE.Mesh
		Cylinder025: THREE.Mesh
		Cylinder025_1: THREE.Mesh
		LIDAR: THREE.Mesh
		Phone_front_camera_module_01: THREE.Mesh
		Circle: THREE.Mesh
		Circle_1: THREE.Mesh
		Phone_screen_frame: THREE.Mesh
		Phone_screen_frame001: THREE.Mesh
		Screw: THREE.Mesh
		Speaker_mesh: THREE.Mesh
		USB_C_port: THREE.Mesh
	}
	materials: {
		['Metal Camera Frame']: THREE.MeshPhysicalMaterial
		['Plastic Camera Frame']: THREE.MeshPhysicalMaterial
		['Glass Tint']: THREE.MeshStandardMaterial
		Glass: THREE.MeshPhysicalMaterial
		['Metal Lens Frame']: THREE.MeshStandardMaterial
		['Glass Lens']: THREE.MeshPhysicalMaterial
		['Plastic Flash']: THREE.MeshStandardMaterial
		LED: THREE.MeshStandardMaterial
		['Plastic Flash Tint']: THREE.MeshStandardMaterial
		['Frosted Glass']: THREE.MeshPhysicalMaterial
		Display: THREE.MeshStandardMaterial
		['Metal Body']: THREE.MeshPhysicalMaterial
		['Plastic Body Antena']: THREE.MeshStandardMaterial
		Metal: THREE.MeshStandardMaterial
		['Glass Camera Control']: THREE.MeshStandardMaterial
	}
}

interface IModelProps {
	screenTextureURL: ScreenTextureURL
}

// Предзагрузка модели и текстур
useGLTF.preload('/Phone.glb')
screenTextureURLs.forEach((url) => {
	useTexture.preload(url)
})

export const PhoneModel = forwardRef<THREE.Group, IModelProps>(({ screenTextureURL }, ref) => {
	const { nodes, materials } = useGLTF('/Phone.glb') as unknown as GLTFResult

	const screenTextures = useTexture(screenTextureURLs as unknown as string[]) as THREE.Texture[]

	useMemo(() => {
		screenTextures.forEach((texture) => {
			texture.flipY = false
			texture.colorSpace = THREE.SRGBColorSpace
		})
	}, [screenTextures])

	const screenTextureIndex = screenTextureURLs.indexOf(screenTextureURL)
	const screenTexture = screenTextureIndex >= 0 ? screenTextures[screenTextureIndex] : undefined

	return (
		<group ref={ref} dispose={null}>
			<mesh
				geometry={nodes.Back_Glass.geometry}
				material={materials['Frosted Glass']}
				position={[0, -0.025, -0.005]}
			/>
			<mesh geometry={nodes.Back_Mic_mesh.geometry} material={materials.Display} />
			<mesh geometry={nodes.Button_Action.geometry} material={materials['Metal Body']} />
			<mesh geometry={nodes.Button_Power_OnOff.geometry} material={materials['Metal Body']} />
			<mesh geometry={nodes.Button_Volume_Down.geometry} material={materials['Metal Body']} />
			<mesh geometry={nodes.Button_Volume_Up.geometry} material={materials['Metal Body']} />
			<mesh geometry={nodes.Camera_Control.geometry} material={materials['Glass Camera Control']} />
			<group position={[0, 0, 0.001]}>
				<mesh geometry={nodes.Cylinder025.geometry} material={materials['Glass Lens']} />
				<mesh geometry={nodes.Cylinder025_1.geometry} material={materials['Plastic Camera Frame']} />
			</group>
			<mesh geometry={nodes.LIDAR.geometry} material={materials['Metal Lens Frame']} />
			<mesh
				geometry={nodes.Phone_front_camera_module_01.geometry}
				material={materials['Metal Lens Frame']}
				position={[-0.0055, 0.07378, 0.004]}
				rotation={[Math.PI / 2, 0, 0]}
				scale={0.0028}
			/>
			<group position={[0.0069, 0.0736, 0.004]} rotation={[Math.PI / 2, 0, 0]} scale={0.0031}>
				<mesh geometry={nodes.Circle.geometry} material={materials.Glass} />
				<mesh geometry={nodes.Circle_1.geometry} material={materials['Metal Lens Frame']} />
			</group>
			<mesh
				geometry={nodes.Phone_screen_frame.geometry}
				material={materials['Glass Tint']}
				position={[0, 0.004, 0.004]}
				scale={1.002}
			/>
			{/* основной экран */}
			<mesh
				geometry={nodes.Phone_screen_frame001.geometry}
				position={[0, 0.004, 0.004]}
				scale={1.002}
				material={screenTexture ? undefined : materials.Glass}
			>
				<meshBasicMaterial map={screenTexture} />
			</mesh>
			<mesh geometry={nodes.Screw.geometry} material={materials.Metal} />
			<mesh geometry={nodes.Speaker_mesh.geometry} material={materials.Display} />
			<mesh geometry={nodes.USB_C_port.geometry} material={materials['Plastic Camera Frame']} />
			<mesh geometry={nodes.Cylinder004.geometry} material={materials['Metal Camera Frame']} />
			<mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Plastic Camera Frame']} />
			<mesh geometry={nodes.Cylinder004_2.geometry} material={materials['Glass Tint']} />
			<mesh geometry={nodes.Cylinder004_3.geometry} material={materials.Glass} />
			<mesh geometry={nodes.Cylinder004_4.geometry} material={materials['Metal Lens Frame']} />
			<mesh geometry={nodes.Lens001.geometry} material={materials['Glass Lens']} />
			<mesh geometry={nodes.Cylinder022.geometry} material={materials['Metal Camera Frame']} />
			<mesh geometry={nodes.Cylinder022_1.geometry} material={materials['Plastic Camera Frame']} />
			<mesh geometry={nodes.Cylinder022_2.geometry} material={materials['Glass Tint']} />
			<mesh geometry={nodes.Cylinder022_3.geometry} material={materials.Glass} />
			<mesh geometry={nodes.Cylinder022_4.geometry} material={materials['Metal Lens Frame']} />
			<mesh geometry={nodes.Lens002.geometry} material={materials['Glass Lens']} />
			<mesh geometry={nodes.Cylinder026.geometry} material={materials['Metal Camera Frame']} />
			<mesh geometry={nodes.Cylinder026_1.geometry} material={materials['Plastic Camera Frame']} />
			<mesh geometry={nodes.Cylinder026_2.geometry} material={materials['Glass Tint']} />
			<mesh geometry={nodes.Cylinder026_3.geometry} material={materials['Metal Lens Frame']} />
			<mesh geometry={nodes.Cylinder026_4.geometry} material={materials.Glass} />
			<mesh geometry={nodes.Lens003.geometry} material={materials['Glass Lens']} />
			<mesh geometry={nodes.Esfera.geometry} material={materials['Plastic Flash']} />
			<mesh geometry={nodes.Esfera_1.geometry} material={materials.LED} />
			<mesh geometry={nodes.Esfera_2.geometry} material={materials['Plastic Flash Tint']} />
			<mesh geometry={nodes.Cube001.geometry} material={materials['Metal Body']} />
			<mesh geometry={nodes.Cube001_1.geometry} material={materials['Plastic Body Antena']} />
			<mesh geometry={nodes.Cube001_2.geometry} material={materials.Metal} />
		</group>
	)
})

PhoneModel.displayName = 'PhoneModel'
