enum ERRORS {
	INVALID_LENGTH = 'INVALID_LENGTH',
	INVALID_EMAIL = 'INVALID_EMAIL',
	UNKNOWN_ERROR = 'UNKNOWN_ERROR',
	MISMATCH = 'MISMATCH',
	ALREADY_CREATED = 'ALREADY_CREATED',
}

export default ERRORS;
